language: node_js
node_js:
- 6.11.0
- 8.9.3
cache:
  directories:
    - node_modules
dist: trusty
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - sudo pip install -r requirements.txt
  - npm install -g gatsby
  - npm install -g babel-cli
  - npm install -g cross-env
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - docker run -d -p 8080:8080 plone/plone.restapi
  - while ! nc -z localhost 8080; do sleep 10; done
  - docker ps -a
  - yarn link
  - (cd tests/gatsby-starter-default && yarn link gatsby-source-plone)
script:
  - make test
notifications:
  email:
    - stollenwerk@kitconcept.com
    - fernandezdealba@kitconcept.com
