language: python
python: 3.6
sudo: required
services:
  - docker
env:
  - NODE_JS=8.11.1
  - NODE_JS=10.1.0
cache:
  pip: true
  directories:
    - node_modules
before_install:
  - nvm install ${NODE_JS}
script:
  - make test
notifications:
  email:
    - stollenwerk@kitconcept.com
    - fernandezdealba@kitconcept.com
