language: node_js
node_js:
  - 8.11.1
  - 10.1.0
cache:
  pip: true
  yarn: true
sudo: required
addons:
  apt:
    packages:
      - python3
      - xsel
services:
  - docker
script:
  - make purge test
notifications:
  email:
    - stollenwerk@kitconcept.com
    - fernandezdealba@kitconcept.com
