language: node_js
node_js:
  - 8.11.1
  - 10.1.0
sudo: required
addons:
  apt:
    packages:
      - python3
services:
  - docker
script:
  - make test
notifications:
  email:
    - stollenwerk@kitconcept.com
    - fernandezdealba@kitconcept.com
