language: node_js
node_js:
- 6.11.0
- 8.9.3
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - sudo pip install -r requirements.txt
  - npm install -g gatsby
  - npm install -g babel-cli
  - npm install -g cross-env
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
script:
  - make test
notifications:
  email:
    - stollenwerk@kitconcept.com
